In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [5]:
from sklearn.linear_model import LinearRegression

df = pd.read_csv('kc_house_data.csv')

In [26]:
df

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0      221900.0         3       1.00         1180      5650     1.0   
1      538000.0         3       2.25         2570      7242     2.0   
2      180000.0         2       1.00          770     10000     1.0   
3      604000.0         4       3.00         1960      5000     1.0   
4      510000.0         3       2.00         1680      8080     1.0   
...         ...       ...        ...          ...       ...     ...   
21608  360000.0         3       2.50         1530      1131     3.0   
21609  400000.0         4       2.50         2310      5813     2.0   
21610  402101.0         2       0.75         1020      1350     2.0   
21611  400000.0         3       2.50         1600      2388     2.0   
21612  325000.0         2       0.75         1020      1076     2.0   

       waterfront  view  condition  grade  sqft_above  sqft_basement  \
0               0     0          3      7        1180              0   
1               0     0          3      7        2170            400   
2               0     0          3      6         770              0   
3               0     0          5      7        1050            910   
4               0     0          3      8        1680              0   
...           ...   ...        ...    ...         ...            ...   
21608           0     0          3      8        1530              0   
21609           0     0          3      8        2310              0   
21610           0     0          3      7        1020              0   
21611           0     0          3      8        1600              0   
21612           0     0          3      7        1020              0   

       yr_built  yr_renovated  sqft_living15  sqft_lot15  
0          1955             0           1340        5650  
1          1951          1991           1690        7639  
2          1933             0           2720        8062  
3          1965             0           1360        5000  
4          1987             0           1800        7503  
...         ...           ...            ...         ...  
21608      2009             0           1530        1509  
21609      2014             0           1830        7200  
21610      2009             0           1020        2007  
21611      2004             0           1410        1287  
21612      2008             0           1020        1357  

[21613 rows x 16 columns]

In [22]:
df.corr()

price  bedrooms  bathrooms  sqft_living  sqft_lot    floors  \
price          1.000000  0.308350   0.525138     0.702035  0.089661  0.256794   
bedrooms       0.308350  1.000000   0.515884     0.576671  0.031703  0.175429   
bathrooms      0.525138  0.515884   1.000000     0.754665  0.087740  0.500653   
sqft_living    0.702035  0.576671   0.754665     1.000000  0.172826  0.353949   
sqft_lot       0.089661  0.031703   0.087740     0.172826  1.000000 -0.005201   
floors         0.256794  0.175429   0.500653     0.353949 -0.005201  1.000000   
waterfront     0.266369 -0.006582   0.063744     0.103818  0.021604  0.023698   
view           0.397293  0.079532   0.187737     0.284611  0.074710  0.029444   
condition      0.036362  0.028472  -0.124982    -0.058753 -0.008958 -0.263768   
grade          0.667434  0.356967   0.664983     0.762704  0.113621  0.458183   
sqft_above     0.605567  0.477600   0.685342     0.876597  0.183512  0.523885   
sqft_basement  0.323816  0.303093   0.283770     0.435043  0.015286 -0.245705   
yr_built       0.054012  0.154178   0.506019     0.318049  0.053080  0.489319   
yr_renovated   0.126434  0.018841   0.050739     0.055363  0.007644  0.006338   
sqft_living15  0.585379  0.391638   0.568634     0.756420  0.144608  0.279885   
sqft_lot15     0.082447  0.029244   0.087175     0.183286  0.718557 -0.011269   

               waterfront      view  condition     grade  sqft_above  \
price            0.266369  0.397293   0.036362  0.667434    0.605567   
bedrooms        -0.006582  0.079532   0.028472  0.356967    0.477600   
bathrooms        0.063744  0.187737  -0.124982  0.664983    0.685342   
sqft_living      0.103818  0.284611  -0.058753  0.762704    0.876597   
sqft_lot         0.021604  0.074710  -0.008958  0.113621    0.183512   
floors           0.023698  0.029444  -0.263768  0.458183    0.523885   
waterfront       1.000000  0.401857   0.016653  0.082775    0.072075   
view             0.401857  1.000000   0.045990  0.251321    0.167649   
condition        0.016653  0.045990   1.000000 -0.144674   -0.158214   
grade            0.082775  0.251321  -0.144674  1.000000    0.755923   
sqft_above       0.072075  0.167649  -0.158214  0.755923    1.000000   
sqft_basement    0.080588  0.276947   0.174105  0.168392   -0.051943   
yr_built        -0.026161 -0.053440  -0.361417  0.446963    0.423898   
yr_renovated     0.092885  0.103917  -0.060618  0.014414    0.023285   
sqft_living15    0.086463  0.280439  -0.092824  0.713202    0.731870   
sqft_lot15       0.030703  0.072575  -0.003406  0.119248    0.194050   

               sqft_basement  yr_built  yr_renovated  sqft_living15  \
price               0.323816  0.054012      0.126434       0.585379   
bedrooms            0.303093  0.154178      0.018841       0.391638   
bathrooms           0.283770  0.506019      0.050739       0.568634   
sqft_living         0.435043  0.318049      0.055363       0.756420   
sqft_lot            0.015286  0.053080      0.007644       0.144608   
floors             -0.245705  0.489319      0.006338       0.279885   
waterfront          0.080588 -0.026161      0.092885       0.086463   
view                0.276947 -0.053440      0.103917       0.280439   
condition           0.174105 -0.361417     -0.060618      -0.092824   
grade               0.168392  0.446963      0.014414       0.713202   
sqft_above         -0.051943  0.423898      0.023285       0.731870   
sqft_basement       1.000000 -0.133124      0.071323       0.200355   
yr_built           -0.133124  1.000000     -0.224874       0.326229   
yr_renovated        0.071323 -0.224874      1.000000      -0.002673   
sqft_living15       0.200355  0.326229     -0.002673       1.000000   
sqft_lot15          0.017276  0.070958      0.007854       0.183192   

               sqft_lot15  
price            0.082447  
bedrooms         0.029244  
bathrooms        0.087175  
sqft_living      0.183286  
sqft_lot         0.718557  
floors          -0.011269  
waterfront 

In [24]:
df['condition'].unique()

array([3, 5, 4, 1, 2], dtype=int64)

In [27]:
df.drop(columns=['yr_built','yr_renovated','sqft_lot15','sqft_lot','condition'],inplace=True)

In [28]:
df

price  bedrooms  bathrooms  sqft_living  floors  waterfront  view  \
0      221900.0         3       1.00         1180     1.0           0     0   
1      538000.0         3       2.25         2570     2.0           0     0   
2      180000.0         2       1.00          770     1.0           0     0   
3      604000.0         4       3.00         1960     1.0           0     0   
4      510000.0         3       2.00         1680     1.0           0     0   
...         ...       ...        ...          ...     ...         ...   ...   
21608  360000.0         3       2.50         1530     3.0           0     0   
21609  400000.0         4       2.50         2310     2.0           0     0   
21610  402101.0         2       0.75         1020     2.0           0     0   
21611  400000.0         3       2.50         1600     2.0           0     0   
21612  325000.0         2       0.75         1020     2.0           0     0   

       grade  sqft_above  sqft_basement  sqft_living15  
0          7        1180              0           1340  
1          7        2170            400           1690  
2          6         770              0           2720  
3          7        1050            910           1360  
4          8        1680              0           1800  
...      ...         ...            ...            ...  
21608      8        1530              0           1530  
21609      8        2310              0           1830  
21610      7        1020              0           1020  
21611      8        1600              0           1410  
21612      7        1020              0           1020  

[21613 rows x 11 columns]

In [33]:
X = df.iloc[:,1:]
X

bedrooms  bathrooms  sqft_living  floors  waterfront  view  grade  \
0             3       1.00         1180     1.0           0     0      7   
1             3       2.25         2570     2.0           0     0      7   
2             2       1.00          770     1.0           0     0      6   
3             4       3.00         1960     1.0           0     0      7   
4             3       2.00         1680     1.0           0     0      8   
...         ...        ...          ...     ...         ...   ...    ...   
21608         3       2.50         1530     3.0           0     0      8   
21609         4       2.50         2310     2.0           0     0      8   
21610         2       0.75         1020     2.0           0     0      7   
21611         3       2.50         1600     2.0           0     0      8   
21612         2       0.75         1020     2.0           0     0      7   

       sqft_above  sqft_basement  sqft_living15  
0            1180              0           1340  
1            2170            400           1690  
2             770              0           2720  
3            1050            910           1360  
4            1680              0           1800  
...           ...            ...            ...  
21608        1530              0           1530  
21609        2310              0           1830  
21610        1020              0           1020  
21611        1600              0           1410  
21612        1020              0           1020  

[21613 rows x 10 columns]

In [35]:
y = df['price']
y

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...   
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64

In [36]:
from sklearn import linear_model

In [37]:
regr = linear_model.LinearRegression()
regr.fit(X,y)

LinearRegression()

In [58]:
p = df.iloc[1,1:]
pnp = np.array(p)
pnp

array([3.00e+00, 2.25e+00, 2.57e+03, 2.00e+00, 0.00e+00, 0.00e+00,
       7.00e+00, 2.17e+03, 4.00e+02, 1.69e+03])

In [59]:
regr.predict([pnp])

array([549936.04225156])